import { palladuim, platinum, silcere, chateau, diamond, eagle, gold, inverted, vintage } from "../assets/ads"

export const trendingCardsData = [
  {
    id: "gold-100g",
    image: gold,
    title: "Gold – 100g",
    price: "$6,480.00",
    details: [
      { label: "Grade", value: "24K (99.99%)" },
      { label: "Quantity", value: "1 Bar" },
      { label: "Location", value: "Zurich, Switzerland" },
      { label: "Custodian", value: "Global Vault Services" },
    ],
    buttonLabel: "Buy",
  },
  {
    id: "silver-eagles",
    image: silcere,
    title: "Silvere American Eagles",
    price: "$720.00",
    details: [
      { label: "Grade", value: "MS-70" },
      { label: "Quantity", value: "20 Coins" },
      { label: "Location", value: "Singapore" },
      { label: "Custodian", value: "Precious Metals Vault" },
    ],
    buttonLabel: "Buy",
  },
  {
    id: "platinum-50g",
    image: platinum,
    title: "Platinum - 50g",
    price: "$1,850.00",
    details: [
      { label: "Grade", value: "99.95% Pure" },
      { label: "Quantity", value: "1 Ingot" },
      { label: "Location", value: "London, UK" },
      { label: "Custodian", value: "Royal Metals Depository" },
    ],
    buttonLabel: "Buy",
  },
  {
    id: "double-eagle-1933",
    image: eagle,
    title: "1933 Double Eagle",
    price: "$18,750.00",
    details: [
      { label: "Grade", value: "MS-65" },
      { label: "Quantity", value: "1 Coin" },
      { label: "Location", value: "New York, USA" },
      { label: "Custodian", value: "Heritage Numismatics" },
    ],
    buttonLabel: "Buy",
  },
  {
    id: "diamond-2ct",
    image: diamond,
    title: "Diamond - 2 Carat",
    price: "$32,400.00",
    details: [
      { label: "Grade", value: "VS1 Clarity, F Color" },
      { label: "Cut", value: "Round Brilliant" },
      { label: "Location", value: "Antwerp, Belgium" },
      { label: "Custodian", value: "Diamond Security Vault" },
    ],
    buttonLabel: "Buy",
  },
  {
    id: "vintage-patek",
    image: vintage,
    title: "Vintage Patek Philippe",
    price: "$22,500",
    details: [
      { label: "Model", value: "Calatrava Ref. 3919" },
      { label: "Year", value: "1985" },
      { label: "Location", value: "Abuja, Nigeria" },
      { label: "Custodian", value: "Personal" },
    ],
    buttonLabel: "Buy",
  },
  {
    id: "inverted-jenny",
    image: inverted,
    title: "Inverted Jenny Stamp",
    price: "$6,480.00",
    details: [
      { label: "Grade", value: "24K (99.99%)" },
      { label: "Quantity", value: "1 Bar" },
      { label: "Location", value: "Zurich, Switzerland" },
      { label: "Custodian", value: "Global Vault Services" },
    ],
    buttonLabel: "Buy",
  },
  {
    id: "palladium-bars",
    image: palladuim,
    title: "Palladium - 1 oz Bars (5)",
    price: "$6,480.00",
    details: [
      { label: "Grade", value: "24K (99.99%)" },
      { label: "Quantity", value: "1 Bar" },
      { label: "Location", value: "Zurich, Switzerland" },
      { label: "Custodian", value: "Global Vault Services" },
    ],
    buttonLabel: "Buy",
  },
  {
    id: "chateau-1945",
    image: chateau,
    title: "1945 Château Mouton Rothschild",
    price: "$6,480.00",
    details: [
      { label: "Grade", value: "24K (99.99%)" },
      { label: "Quantity", value: "1 Bar" },
      { label: "Location", value: "Zurich, Switzerland" },
      { label: "Custodian", value: "Global Vault Services" },
    ],
    buttonLabel: "Buy",
  },
];